{
 "title": "Sustainability dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total carbon dioxide",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT carbon_dioxide FROM uploaded_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total eco costs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT total_eco_costs FROM uploaded_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "CO2 Emissions by Category",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT category, carbon_dioxide FROM uploaded_data GROUP BY carbon_dioxide, category LIMIT 50 "
    }
   ]
  },
  {
   "title": "Eco cost mean values",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT eco_costs_e1 AS \"E1\", eco_costs_e2 AS \"E2\", eco_costs_e3 AS \"E3\", eco_costs_e4 AS \"E4\", eco_costs_e5 AS \"E5\" FROM uploaded_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "Data entries",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT name, category, unit, quantity, carbon_dioxide, total_eco_costs, eco_costs_e1, eco_costs_e2, eco_costs_e3, eco_costs_e4, eco_costs_e5 FROM uploaded_data LIMIT 50 "
    }
   ]
  }
 ]
}