# Generated by Django 5.1.6 on 2025-09-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proces',
            fields=[
                ('lci_number', models.IntegerField(primary_key=True, serialize=False)),
                ('unit', models.TextField()),
                ('process_name', models.TextField()),
                ('carbon_dioxide', models.IntegerField()),
                ('total_eco_costs', models.IntegerField()),
                ('eco_costs_e1', models.IntegerField()),
                ('eco_costs_e2', models.IntegerField()),
                ('eco_costs_e3', models.IntegerField()),
                ('eco_costs_e4', models.IntegerField()),
                ('eco_costs_e5', models.IntegerField()),
            ],
        ),
    ]
