# Generated by Django 5.1.6 on 2025-09-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proces',
            name='carbon_dioxide',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='proces',
            name='eco_costs_e1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='proces',
            name='eco_costs_e2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='proces',
            name='eco_costs_e3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='proces',
            name='eco_costs_e4',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='proces',
            name='eco_costs_e5',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='proces',
            name='total_eco_costs',
            field=models.FloatField(),
        ),
    ]
