# Generated by Django 5.1.6 on 2025-09-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_alter_proces_carbon_dioxide_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category', models.TextField()),
                ('quantity', models.FloatField()),
                ('unit', models.TextField()),
                ('carbon_dioxide', models.FloatField()),
                ('total_eco_costs', models.FloatField()),
                ('eco_costs_e1', models.FloatField()),
                ('eco_costs_e2', models.FloatField()),
                ('eco_costs_e3', models.FloatField()),
                ('eco_costs_e4', models.FloatField()),
                ('eco_costs_e5', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'uploaded_data',
            },
        ),
    ]
